### ISSUE TITLE
Login and register using social accounts (G+, FB, Twitter, etc.)

### ISSUE THREAD

**Issue by dashohoxha** [Labdoo/Labdoo#79]
I think that it makes it easy for users to login if they don't have to create and remember yet-another-password, but can use instead any of their existing accounts on G+, FB, Twitter, GitHub, LinkedIn, etc.

See how it looks like on my application: https://btranslator.org/user/login You can test it if you wish.

If you think this is useful, I can help you implement something similar (since I already know how to do it). However you will have to take care of the configurations yourself (this includes creating apps on FB, G+, etc. there are docs about how to do it).

**Comment by dashohoxha** [comment]
The most straightforward way to implement this is to copy and use this feature module:
https://github.com/B-Translator/btr_server/tree/master/modules/features/btr_hybridauth

However I would replace first **btr** with **lbd** everywhere (although this may not be strictly required).

And then these lines need to be appended to the make file:
https://github.com/B-Translator/btr_server/blob/master/btr_server.make#L106-114 
```
;--------------------
; HybridAuth
;--------------------

projects[hybridauth] = 2.12

libraries[hybridauth][directory_name] = hybridauth
libraries[hybridauth][download][type] = get
libraries[hybridauth][download][url] = https://github.com/hybridauth/hybridauth/archive/v2.2.1.tar.gz
```

**Comment by dashohoxha** [comment]
Hybridauth has also some hooks which can be used to customize the registration form etc. (when registration is done through G+, FB, etc.). For my project they look like this:
 - https://github.com/B-Translator/btr_server/blob/master/modules/custom/btrUser/include/hybridauth.inc
 - https://github.com/B-Translator/btr_server/blob/master/modules/custom/btrUser/btrUser.module#L13

But they are specific to each application.
Hybridauth has information about the hooks that it provides, when they are called, what they can be used for etc.

**Comment by jrosgiralt** [comment]
For now we are not going to implement this feature, we want to keep user information at its minimum, including avoiding linking labdoo accounts with other's users social media accounts. Am cleaning up some long standing tickets, let's move any discussions to Labdoo's own ticket system if needed under https://www.labdoo.org/content/software-development/activities. Thks.
