### ISSUE TITLE
Cleanup old feature branches.

### ISSUE THREAD

**Issue by dashohoxha** [Labdoo/Labdoo#80]
I think that after feature branches have been merged to master, they can be safely removed. GitHub even has a button for deleting an old branch, after the pull request has been merged. The history of development is not lost, since all the old pull requests are still there, although they are closed:
https://github.com/Labdoo/Labdoo/pulls?q=is%3Apr+is%3Aclosed

**Comment by jrosgiralt** [comment]
I agree that the features are creating noise. On the other hand I know other well established open source projects that don't remove their branch features from github. One advantage is that you can easily identify some branch by using its feature branch. I think we can remove some that are less important and leave some. Soon i will do a pass and clean up those that are less relevant.

**Comment by dashohoxha** [comment]
Once you merge a **development** branch to the master, and then add more commits to the master, the old branch serves no purpose at all, except for confusion.
If it is a **fork** branch, that will never be merged to master (but master can be merged to it), then it is a different story.
Anyway, this is just my opinion.
