### ISSUE TITLE
Social share buttons

### ISSUE THREAD

**Issue by dashohoxha** [Labdoo/Labdoo#82]
Could be nice if some pages or photos had buttons for sharing to social networks. This would make it easier for people to share to their circles, and could increase the awareness about the project.

**Comment by labdoo-jrg** [comment]
Dashamir, we are using Labdoo teams to report feature requests. Could you please write these issues directly to our "Software Development" Team?

Go to: https://www.labdoo.org/teams
Subscribe to Soft Dev team
Once inside the Soft Dev team, click on "Start task" icon located on the right column

You can assign these tasks under my user name 'jordi.ros'

PS: our 2.0 teams interface engine is based on 'organic groups'

**Comment by jrosgiralt** [comment]
This was implemented some time ago. Also, we use Labdoo's own ticket system so i am closing this and other tasks. Thanks.
