### ISSUE TITLE
Change "BlackBerry Pi" to "Raspberry Pi"

### ISSUE THREAD

**Issue by der-eismann** [Labdoo/Labdoo#88]
I think someone was a bit sleepy, when he added the device type "BlackBerry Pi" when tagging a new device. Since this device doesn't exist - only a BlackBerry smartphone or a Raspberry Pi computer - it should be corrected.

**Comment by jrosgiralt** [comment]
This is the current list of devices. Notice that the human readable tag is the one on the right side and that is correct 'Raspberry Pi'. The incorrect one is the machine name, marked as 'blackberryPi', that was a typo introduced some time ago but since these fields are being used, we can't change them anymore. But this is not a problem as that's the machine name, which could be anything.

    laptop|Laptop
    desktop|Desktop
    internetTablet|Internet tablet
    androidTablet|Android tablet
    ipad|iPad
    ebook|eBook
    smartphone|SmartPhone
    googlePhone|Android phone
    iphone|iPhone
    blackberry|BlackBerry
    diyDevice|Do-it-yourselve device
    arduino|Arduino
    blackberryPi|Raspberry Pi

**Comment by dashohoxha** [comment]
If blackberryPi is stored in DB, it can be changed with a simple UPDATE query. It is kind of surgical operation but I believe that it can be done, and it is not too difficult.

**Comment by labdoo-org** [comment]
Agreed, we just have not done that (we avoid touching directly the DB
unless there is a strong compelling reason)

**Comment by dashohoxha** [comment]
Yes, this is not a strong reason.
But I am a bit of perfectionist. And I fall often in the trap of making small changes. And sometimes I find myself in troubles.

**Comment by der-eismann** [comment]
Then it looks like it's related to the translations. On the English page the device type says "Raspberry Pi", in German it's "BlackBerry Pi". Maybe someone can fix this line? I've never worked with *.po files before:
https://github.com/Labdoo/Labdoo/blob/master/translations/po-files/fields-de.po#L226

**Comment by labdoo-org** [comment]
I have just corrected this. Thanks for noticing and letting us know.

Please check if things are now corrected:
https://www.labdoo.org/de/node/add/laptop

The fix:
https://github.com/Labdoo/Labdoo/commit/932137182e0c96e8b70e8d5f58be8e5653f3c981

**Comment by der-eismann** [comment]
Looks good to me, thanks for fixing :)
